version: "3"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=urubu
      - MONGO_INITDB_ROOT_PASSWORD=pix
    volumes:
      - mongo-db:/data/db
    ports:
    - "27018:27017"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - USER_DB=urubu
      - PASSWORD_DB=pix
      - CONNECTION_DB=mongo:27017/urubu_pix
    command: npm start

volumes:
  mongo-db:


